<message name="getTermRequest">
  <part name="term" type="xs:string"/>
</message>

<message name="getTermResponse">
  <part name="value" type="xs:string"/>
</message>

<portType name="tns:GetDataPortType">
  <operation name="tns:GetData">
    <input message="getRequest"/>
    <output message="getResponse"/>
  </operation>
</portType>